### ISSUE TITLE
把slimtrie 导入进来

### ISSUE THREAD

**Issue by drmingdrmer** [openacid/slim#1]
几个相关的数据结构: 

- slim.baseTrie 普通的trie
- slim.SlimTrie 压缩后的16 branch的trie
- slim.CompactedArray 压缩数组
- slim.bit bit操作函数包

各位看看下, 名字ok不?

**Comment by lishulong** [comment]
首字母都是大写的吧？

slim.bit bit操作函数包
叫 slim.BitWise 咋样?

**Comment by drmingdrmer** [comment]
> 首字母都是大写的吧？

baseTrie是个数据结构, 不确认是否需要对外. 如果需要就大写B.

> 叫 slim.BitWise 咋样?

slim.bit是个package或文件(文件的话就直接属于slim的package), 不是数据结构, 所以貌似不用大写, 里面的函数是大写. 感觉bitwise有点长... 只用bit你觉得会有歧义吗?
