### ISSUE TITLE
Trie are missing keys

### ISSUE THREAD

**Issue by aaaton** [openacid/slim#104]
I created a trie with ~70k unique keys and corresponding integer values with `trie.NewSlimTrie(encode.Int{}, keys, values)`
I then measured how many of my keys were in the trie. I was lacking roughly 14%

**To Reproduce**
This doesn't return the same number of keys, but shows the problem:
```
func TestSlimTrie(t *testing.T) {
	var keys []string
	var indexes []int
	for i := 0; i < 70000; i++ {
		keys = append(keys, randStringRunes(10))
		indexes = append(indexes, i)
	}
	sort.Strings(keys)
	tr, err := trie.NewSlimTrie(encode.Int{}, keys, indexes)
	if err != nil {
		t.Error(err)
		return
	}
	count := 0
	for _, key := range keys {
		_, found := tr.Get(key)
		if !found {
			count++
		}
	}
	if count > 0 {
		t.Errorf("Couldn't find %f%% of the keys entered. Missing %d keys", float64(count)/float64(len(keys))*100, count)
	}
}
```

**Environment:**
 - MacOS
 - openacid/slim v0.5.5

**Language:**
 - go 1.12

**Comment by drmingdrmer** [comment]
Sorry for this bug. It's my incaution In `v0.5.5` I enlarged trie size to int32 but somewhere I missed type conversion. A patch will be soon to be applied.

Thank you for letting me know this issue 😸

**Comment by drmingdrmer** [comment]
`v0.5.6` fixed this bug with test added.
Let me know whether it works well or not with your environment, please:)

**Comment by aaaton** [comment]
It works now. Thank you
