### ISSUE TITLE
Possible to show GC performance on... a few variations?

### ISSUE THREAD

**Issue by superdolt** [openacid/slim#155]
1. Possible to show GC performance on... a few variations?
2. Possible to provide example usage with a "package main" example instead?
3. pls show alloc / op and bytes alloc / op information. thx
4. how do you gzip-size? what do you mean by gzip-size on the front page readme? how do you gzip the data?
5. how do you do delete function or insertion one by one?
6. suggestion on how to do lru with this slim trie?

**Comment by drmingdrmer** [comment]
> 1. Possible to show GC performance on... a few variations?

How to benchmark the GC performance? I've not yet done this before. 🤔 

> 2. Possible to provide example usage with a "package main" example instead?

I did not get what you want.

> 3. pls show alloc / op and bytes alloc / op information. thx

Detailed benchmark can be obtained by running test with `-bench` or `-benchmem`.
A query operation does not alloc to fetch a fixed type return value, such as `u16`.
The more generic query API that returns `interface{}` allocates one `interface` for the return value.
Memory allocation during creation is hard to estimate, let the benchmark tell.

> 4. how do you gzip-size? what do you mean by gzip-size on the front page readme? how do you gzip the data?

Just the default `gzip <fn>`

> 5. how do you do delete function or insertion one by one?

slimtrie is static thus it does not support deletion after creation.

> 6. suggestion on how to do lru with this slim trie?

LRU is not possible with a static data type.
