### ISSUE TITLE
文档： 如何更新/删除key

### ISSUE THREAD

**Issue by andypeng2015** [openacid/slim#156]
**What document to add**

这是一个很好的索引设计，感谢开源

从介绍中（ https://blog.openacid.com/tech/algorithm/slimtrie-impl/ ）了解到，SlimTrie只索引静态数据，数据生成之后在使用阶段不修改。

请问：
1: 在实际生产中，是不是需要一个临时数据结构（类似LSM tree里面的SSTable）去保存N个文件， 然后写入SlimTrie？有没有示例代码？

2: 在实际生产中，要对已经存在SlimTrie的key进行更新/删除， 如何进行？是不是要重建SlimTrie？有没有示例代码？

再次感谢

**Comment by drmingdrmer** [comment]
1. slim 可以看做是一个sstable, 设计上就是针对sstable的功能做的, 它的数据来源应该是内存中的memtable.
2. 修改不了.

写入的例子可以在测试和example里找到, 类似这个:
https://github.com/openacid/slim/blob/main/trie/example_mem_usage_test.go

**Comment by andypeng2015** [comment]
@drmingdrmer 谢谢答疑，请问有没有开源的production code用到slim？想了解一下实现的细节

**Comment by drmingdrmer** [comment]
目前有几个应用场景都是闭源的. 没法提供代码样例. 抱歉

**Comment by andypeng2015** [comment]
> 目前有几个应用场景都是闭源的. 没法提供代码样例. 抱歉

没关系 谢谢
