### ISSUE TITLE
Probabilistic structure (bloom-filter-like) or a guaranteed structure?

### ISSUE THREAD

**Issue by dumblob** [openacid/slim#164]
**What document to add**

I could not find any information explaining whether this "slim" structure is a probabilistic one or not. Trie is not probabilistic and thus provides **guarantees**. But in the redame of "slim" there is a mention of FPR (false positive rate) so I wonder whether this is actually a trie-like structure (i.e. all is guaranteed) or rather a bloom-like structuer (i.e. no guarantees).

**Additional context**

N/A

**Comment by drmingdrmer** [comment]
It can be both: with the `Complete` option there won't be false positives:
https://github.com/openacid/slim/blob/d27f7e916f6b70fc0b065fb835a7cde5e4a40db9/trie/slimtrie.go#L132-L140

To use it as a filter, set `InnerPrefix`, `LeafPrefix` and `Complete` to false(`Complete` implies `InnerPrefix==true` and `LeafPrefix==true`). Then slim won't store any single label branch in the trie it builds.

With  `InnerPrefix==true`, it does not reduce a single label branch that leads to an inner node.

With  `LeafPrefix==true`, it does not reduce a single label branch that leads to a leaf node.

E.g.:

```
// Complete
InnerPrefix: true
LeafPrefix: true
^ -a-> 1 -b-> $
 `-c-> 2 -x-> 3 -y-> $
               `-z-> $

InnerPrefix: true
LeafPrefix: false
^ -a-> $
 `-c-> 2 -x-> 3 -y-> $
               `-z-> $

InnerPrefix: false
LeafPrefix: true
^ -a-> 1 -b-> $
 `-c-> 3 -y-> $
        `-z-> $

InnerPrefix: false
LeafPrefix: false
^ -a-> $
 `-c-> 3 -y-> $
        `-z-> $```
```

**Comment by dumblob** [comment]
Ah, thanks for explanation! Could you add it to the readme and specify how the benchmark chart was obtained (wheth with `Complete` or without)?

**Comment by dumblob** [comment]
Thanks. I think `readme.md` is now more readable.

Will you also **explicitly** specify if the charts (`ns/Get()` and `bits/key`) in the https://github.com/openacid/slim#performance-and-memory-overhead section were performed with `Complete` or without?

**Comment by drmingdrmer** [comment]
> Will you also **explicitly** specify if the charts (`ns/Get()` and `bits/key`) in the https://github.com/openacid/slim#performance-and-memory-overhead section were performed with `Complete` or without?

Thanks for reminding me.

The benchmark is done in the filter mode. The data structure that is used in the benchmark is a list of `(key,value)` and a `slim` is used as an index to locate a key-value record.
