### ISSUE TITLE
Testing imports leak into trie package

### ISSUE THREAD

**Issue by Luit** [openacid/slim#75]
Looking at the imports of the github.com/openacid/slim/trie package, I see multiple packages that appear to be used for testing. Among them are `testing`, `unsafe`, `github.com/openacid/slim/trie/benchmark`, `github.com/google/btree` and more. This appears to be because of the file `trie/test_utils.go`. If this file were called `trie/utils_test.go` these imports disappear.

**To Reproduce**
1. https://godoc.org/github.com/openacid/slim/trie?imports

**Expected behavior**
I expected a list of imports without `testing`

**Actual behavior**
Includes `testing` and a few others that probably don't belong there.

I think this can be fixed by renaming the file, but I'm not 100% sure, because I don't know the code too well.

**Comment by drmingdrmer** [comment]
Thank you for reporting this issue. 😃 
Yes, the codes for benchmark and testing are not quite clean for now.
I'd have a look and refactor it to make the import tree cleaner.

**Comment by drmingdrmer** [comment]
The dependency graph has been cleaned after moving benchmarking utilities into a separate subdirectory.

`test_util.go` is now moved to `trie/benchmark`.
