### ISSUE TITLE
Trie Node: add field `squash`

### ISSUE THREAD

**Issue by drmingdrmer** [openacid/slim#83]
**Trie Node: add field `squash`**

Currently the (not slim) Trie node is defined as follow:
```go
type Node struct {
	Children map[int]*Node
	Branches []int
	Step     uint16
	Value    interface{}

	isStartLeaf bool

	NodeCnt int
}
```

Add a field `squash bool`, to indicate this trie to squash preceding branches every time after `Append` a new key.

When creating child node, the child should inherit the `squash` value from its parent.

**Benifit**:

- Thus this simplifies the method `Append()`: user does not need to pass a `squash` argument any more.

**Comment by wenbobuaa** [comment]
finished in #84
